# Permalinks
permalink:        /:year/:month/:title/

# Setup
title:            blukat29
url:              http://blukat29.github.io
baseurl:          /

author:
  name:           'blukat29'
  url:            https://github.com/blukat29

paginate: 5
paginate_path: /page/:num/

excerpt_separator: <!--more-->

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
sass:
  style: compressed

google_analytics: G-EDQ47ETX6E

comment: true

# Gems
gems:
  - jekyll-paginate
