# Permalinks
permalink:        /:year/:month/:title/

# Setup
title:            blukat29
url:              http://blukat29.github.io

author:
  name:           'blukat29'
  url:            https://github.com/blukat29

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true

google_analytics: UA-85597106-1

comment:           false
