# Permalinks
permalink:        /:year/:month/:title/

# Setup
title:            blukat29
tagline:          'blog'
description:      'blog.'
url:              http://blukat29.github.io

author:
  name:           'blukat29'
  url:            https://github.com/blukat29

markdown: kramdown

comment:           false
